# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration production
  displayName: 'npm install and build'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'acrdotnetconnection'
#     repository: 'angularapp'
#     command: 'build'
#     Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
     containerRegistry: 'acrconnectiondemo'
     repository: 'angularapp'
     command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '/'
    Contents: |
      kubedeploy.yaml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'     
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'