apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: 
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICJhY3Jhc3Nlc3NtZW50dXN0cmVnc2l0cnkuYXp1cmVjci5pbyI6IHsNCiAgICAgICAgInVzZXJuYW1lIjogImFjckFzc2Vzc21lbnRVc3RSZWdzaXRyeSIsDQogICAgICAgICJwYXNzd29yZCI6ICIySHFXZlE5RmhIRkFUWVZIRlZmZlNIbGR1YmNrVyttSythTFMwRHNDbzkrQUNSRGVCZVdEIiwNCiAgICAgICAgImF1dGgiOiAiWVdOeVFYTnpaWE56YldWdWRGVnpkRkpsWjNOcGRISjVPakpJY1ZkbVVUbEdhRWhHUVZSWlZraEdWbVptVTBoc1pIVmlZMnRYSzIxTEsyRk1VekJFYzBOdk9TdEJRMUpFWlVKbFYwUT0iDQogICAgICB9DQogICAgfQ0KICB9DQogIA==